# Generated by Django 4.2 on 2024-08-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/user_profile.png', upload_to='images/'),
        ),
    ]
