# Generated by Django 4.2 on 2024-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag_name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="hashtag",
            field=models.ManyToManyField(
                related_name="hashtag_product", to="products.hashtag"
            ),
        ),
    ]
